FROM node:18-alpine


ARG NEXT_PUBLIC_NODE_ENV
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_API3_BASE_URL
ARG NEXT_PUBLIC_WS_SERVER_URL
ARG NEXT_PUBLIC_STACK_BASE_URL
ARG NEXT_PUBLIC_STORE_BASE_URL
ARG NEXT_PUBLIC_TOKEN_CREATORS
ARG NEXT_PUBLIC_SLIDESHOW_BASE_URL
ARG NEXT_PUBLIC_SEARCH_BASE_URL
ARG NEXT_PUBLIC_STUDIO_BASE_URL
ARG NEXT_PUBLIC_ASSET_STORAGE_URL
ARG NEXT_PUBLIC_GENERAL_STORAGE_URL
ARG NEXT_PUBLIC_STORES_STORAGE_URL
ARG NEXT_PUBLIC_WEB3_NETWORK_TYPE
ARG NEXT_PUBLIC_WEB3_PRIVATE_KEY
ARG NEXT_PUBLIC_WEB3_NETWORK_RPC_ADDRESS
ARG NEXT_PUBLIC_EXPLORER_BASE_URL
ARG NEXT_PUBLIC_WAGMI_APP_NAME
ARG NEXT_PUBLIC_WAGMI_PROJECT_ID

ENV NEXT_PUBLIC_NODE_ENV=${NEXT_PUBLIC_NODE_ENV}
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_API3_BASE_URL=${NEXT_PUBLIC_API3_BASE_URL}
ENV NEXT_PUBLIC_WS_SERVER_URL=${NEXT_PUBLIC_WS_SERVER_URL}
ENV NEXT_PUBLIC_STACK_BASE_URL=${NEXT_PUBLIC_STACK_BASE_URL}
ENV NEXT_PUBLIC_STORE_BASE_URL=${NEXT_PUBLIC_STORE_BASE_URL}
ENV NEXT_PUBLIC_TOKEN_CREATORS=${NEXT_PUBLIC_TOKEN_CREATORS}
ENV NEXT_PUBLIC_SLIDESHOW_BASE_URL=${NEXT_PUBLIC_SLIDESHOW_BASE_URL}
ENV NEXT_PUBLIC_SEARCH_BASE_URL=${NEXT_PUBLIC_SEARCH_BASE_URL}
ENV NEXT_PUBLIC_STUDIO_BASE_URL=${NEXT_PUBLIC_STUDIO_BASE_URL}
ENV NEXT_PUBLIC_ASSET_STORAGE_URL=${NEXT_PUBLIC_ASSET_STORAGE_URL}
ENV NEXT_PUBLIC_GENERAL_STORAGE_URL=${NEXT_PUBLIC_GENERAL_STORAGE_URL}
ENV NEXT_PUBLIC_STORES_STORAGE_URL=${NEXT_PUBLIC_STORES_STORAGE_URL}
ENV NEXT_PUBLIC_WEB3_NETWORK_TYPE=${NEXT_PUBLIC_WEB3_NETWORK_TYPE}
ENV NEXT_PUBLIC_WEB3_PRIVATE_KEY=${NEXT_PUBLIC_WEB3_PRIVATE_KEY}
ENV NEXT_PUBLIC_WEB3_NETWORK_RPC_ADDRESS=${NEXT_PUBLIC_WEB3_NETWORK_RPC_ADDRESS}
ENV NEXT_PUBLIC_EXPLORER_BASE_URL=${NEXT_PUBLIC_EXPLORER_BASE_URL}
ENV NEXT_PUBLIC_WAGMI_APP_NAME=${NEXT_PUBLIC_WAGMI_APP_NAME}
ENV NEXT_PUBLIC_WAGMI_PROJECT_ID=${NEXT_PUBLIC_WAGMI_PROJECT_ID}

EXPOSE 3000
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

CMD [ "npm", "start" ]
